#!/usr/bin/env bash
# Muster — Reset (nuke everything and start over)

root="$(find_comms_root)" || die "No muster project found."

COMMS_DIR="$root/comms"
AGENTS_DIR="$root/.opencode/agents"

echo ""
warn "This will delete all muster-generated files and start fresh."
echo -e "${DIM}  comms/              (team config, journals, notes)"
echo -e "  .opencode/agents/  (agent definitions)"
echo -e "  CLAUDE.md          (legacy, if present)"
echo -e "  AGENTS.md will be regenerated by init${RESET}"
echo ""
read -rp "Are you sure? [y/N]: " confirm
confirm="$(echo "${confirm:-n}" | tr '[:upper:]' '[:lower:]')"
[ "$confirm" != "y" ] && die "Cancelled."

rm -rf "$COMMS_DIR"
rm -rf "$AGENTS_DIR"

# Clean up legacy files from v0.1.x
rm -f "$root/CLAUDE.md"
rm -f "$root/.muster-status.sh"
rm -f "$root/.muster-dispatch.pid"
rm -f "$root/.muster-dashboard.pid"
rm -f "$root/.muster-dashboard-port"
rm -f "$root/.muster-title.sh"

# Remove stale AGENTS.md so init generates a clean one
rm -f "$root/AGENTS.md"

success "Cleared. Run 'muster init' to start fresh."
echo ""
